# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8f6c6d288c6faeac1b7c1de3d719e2a09bb0aa418dcd3d857e0022dcdbd6d971d8d2565b93be5e8d6a42fa9d2732ec83b0f922e14397f53b373395322dd23b8

test:
  secret_key_base: e5bfed3539e4ac5de260ede1a6ceb473fb94b0091b4cd8824009e254df944ac45d77c20f701b4e0b1b24e8a98bfd269e80d367120432eca575f576be1aca6036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
